name: PluginCite
version: '1.0'
main: org.plugins.plugincitev1.Main
author: 'TableIkea_'
api-version: '1.21'
commands:
  teams:
    description: Teams Management
    aliases: ['equipe','team']
    permission: player.teams.execute

permissions:
    player.teams.execute:
        description: Allows players to manage teams
        default: true
    player.teams.admin:
        description: Allows players to manage teams as an admin
        default: op